spring:
  datasource:
    url: jdbc:h2:mem:personsdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/local/changelog.yml